import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthSession from "./components/provider/authSession";
import QueryProviders from "./components/provider/queryClientProvider";
import Header from "@/layout/header/page";
import Footer from "@/layout/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProviders>
      <AuthSession>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            {children}
            <Footer/>
          </body>
        </html>
      </AuthSession>
    </QueryProviders>
  );
}
