import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthSession from "./components/provider/authSession";
import QueryProviders from "./components/provider/queryClientProvider";
import Header from "@/layout/header/page";
import Footer from "@/layout/footer/page";
import { Box } from "lucide-react";
import { Stack } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProviders>
      <AuthSession>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            <Stack
            sx={{
              width:'100%'
            }}
            >
            <Stack
            sx={{
              width:'1200px',
              margin:'0 auto'
            }}
            >
            {children}
            </Stack>
            </Stack>
            {/* <Footer/> */}
          </body>
        </html>
      </AuthSession>
    </QueryProviders>
  );
}
